#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'

def sys(*args)
  STDERR.puts "> #{args.join(' ')}"
  result = system(*args)
  unless result
    raise IOError.new "command returned #{$?.exitstatus}"
  end
end

def cd(dir, &blk)
  FileUtils.cd(dir) do
    STDERR.puts "> (cd #{dir}"
    blk.call()
    STDERR.puts "> )"
  end
end

yml = YAML.load File.open 'stack.yaml'
version = `cabal info .`.match(/\A\*\s+[\w-]+-([\d\.]+)\s+/) do |md|
  md[1]
end or raise IOError.new "#{$0}: couldn't parse cabal info"

unless ARGV.length == 2
  STDERR.puts "Usage: #{$0} [platform] [executable name]"
  STDERR.puts "Platforms: windows, mac, mac-app, linux"
  exit 1
end
platform = ARGV[0]
exe      = ARGV[1]

# http://stackoverflow.com/a/171011
module OS
  def OS.windows?
    (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end

  def OS.mac?
   (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def OS.unix?
    !OS.windows?
  end

  def OS.linux?
    OS.unix? and not OS.mac?
  end
end

if OS.mac? && platform == 'mac'

  outdir = '.stack-work/release/mac'
  FileUtils.rm_rf outdir
  sys "stack setup"
  sys "stack build"
  FileUtils.mkdir_p outdir
  FileUtils.cp `stack exec which #{exe}`.chomp, outdir
  sys "strip .stack-work/release/mac/#{exe}"
  sys "dylibbundler -cd -of -b -x #{outdir}/#{exe} -d #{outdir} -p '@executable_path'"

elsif OS.mac? && platform == 'mac-app'

  outdir = '.stack-work/release/mac-app'
  FileUtils.rm_rf outdir
  sys "stack setup"
  sys "stack build"
  contents = "#{outdir}/#{exe}.app/Contents"
  FileUtils.mkdir_p "#{contents}/MacOS"
  FileUtils.mkdir_p "#{contents}/libs"
  FileUtils.cp `stack exec which #{exe}`.chomp, "#{contents}/MacOS"
  sys "strip #{contents}/MacOS/#{exe}"
  sys "dylibbundler -cd -of -b -x #{contents}/MacOS/#{exe} -d #{contents}/libs -p '@executable_path/../libs'"
  File.open("#{contents}/Info.plist", 'w') do |f|
    f.puts <<-XML
      <plist version="1.0">
      <dict>
        <key>CFBundleExecutable</key>
        <string>#{exe}</string>
        <key>CFBundleName</key>
        <string>#{exe}</string>
      </dict>
      </plist>
    XML
  end

elsif OS.unix? && platform == 'windows'

  outdir = '.stack-work/release/windows'
  FileUtils.rm_rf outdir
  FileUtils.mkdir_p outdir
  ENV['WINEPREFIX'] = "#{Dir.pwd}/.stack-work/release/wine"
  ENV['WINEDEBUG'] = 'fixme-all'
  sys 'wine wineboot'
  begin
    sys 'wine stack --version'
  rescue
    sys 'wget https://github.com/commercialhaskell/stack/releases/download/v0.1.1.0/stack-0.1.1.0-i386-windows.zip -O stack.zip'
    sys 'unzip stack.zip'
    FileUtils.rm 'stack.zip'
    FileUtils.mv 'stack.exe', "#{ENV['WINEPREFIX']}/drive_c/windows/system32/stack.exe"
  end
  sys 'wine stack setup'
  sys 'wine stack build'
  FileUtils.cp Dir[".stack-work/install/i386-windows/*/*/bin/#{exe}.exe"][0], outdir

else
  STDERR.puts "#{$0}: unsupported platform combination"
  exit 1
end

extra = Dir['README*', 'LICENSE*', 'COPYING*']
extra.each { |f| FileUtils.cp f, outdir }
cd outdir do
  sys "zip -r ../#{exe}-v#{version}-#{platform}.zip ./*"
end
